using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Todoist.Net.Models
{
    /// <summary>
    /// Represents a response that contains the results of executed synchronization transaction.
    /// </summary>
    public class SyncTransactionResponse : SyncResourcesResponse
    {
        /// <summary>
        /// Gets the synchronization status for each command, mapped by command ID.
        /// </summary>
        /// <remarks>
        /// Contains the result of each executed command with its corresponding GUID as the key.
        /// </remarks>
        [JsonPropertyName("sync_status")]
        public Dictionary<Guid, CommandResult> SyncStatus { get; internal set; }

        /// <summary>
        /// Gets the mapping of temporary IDs to their permanent IDs assigned by the server.
        /// </summary>
        /// <remarks>
        /// Temporary IDs provided in the request are mapped to permanent IDs generated by the server.
        /// </remarks>
        [JsonPropertyName("temp_id_mapping")]
        public Dictionary<Guid, string> TempIdMappings { get; internal set; }
    }
}
